### PR TITLE
Replace PARAM macros with new Fifo accessor

### PR DESCRIPTION
**Pull request by ghost**
I have a patch to upgrade some Fifo code (https://github.com/genodelabs/genode/issues/3135) in Seoul, but I have problems on staging, perhaps related to `printf`. See https://github.com/ehmry/genode/commit/193aa0a2747cb85141a84f8105f7a535a8cb9fdc.

```
[init -> seoul] VMM: unimpl GRP case a06feae8bf83af60bf8a7110 at -1080538136
[init -> seoul] VMM: decode fault a06feb18
[init -> seoul] Error: VMM PANIC!
```

### CODE REVIEW

**Comment by alex-ab** [comment]
Looking at the implementation of Utcb_guard, I fear that it is not equivalent with the full manual copy of the utcb as done before. I presume that you corrupt the utcb (by losing some data) and therefore run into trouble.

Regarding the actual Seoul patch - the include/nul/motherboard.h file is used by several user-lands and therefore must not be Genode specific. I would like see it unchanged. All changes should go to genode/include/service/params.h.

**Comment by ghost** [comment]
@alex-ab I have a new version that does not touch non-Genode code.

**Comment by alex-ab** [comment]
@ehmry: nice - please use cd9fcb7a1eb6e1db3aa12c78cdcadb4492dc13dc respectively genode_19_02 branch and re-test.

**Comment by ghost** [comment]
The patch applies to the `genode_19_02` branch as well, but I can't get `genode/repos/ports/src/app/seoul/nova_user_env.cc` to work right, I've just been printing the format strings for testing.

**Pull request closed without merging**
